sudo: required

arch:
  packages:
    # pacman packages
    - libsodium
  script:
    - "./build.sh"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
