sudo: required

arch:
  packages:
    # pacman packages
    - qt5-base
    - qt5-declarative
    - qt5-quickcontrols
    - qt5-quickcontrols2
    - qt5-tools
    - python
    - wget
  script:
    - "./build.sh"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
